version: '3.0'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
  rasa:
    build: rasa_backend/.
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: >
        run 
        --enable-api
        --cors "*"
  app:
    build: /.
    expose:
    - 5055